# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-27 05:44
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=200, verbose_name='照片说明')),
                ('img', models.FileField(max_length=300, upload_to='%Y%m/file/')),
                ('thumb_img', models.ImageField(blank=True, max_length=300, null=True, upload_to='%Y%m/file_thumb/')),
                ('types', models.IntegerField(choices=[(0, '图片文件')], default=0, verbose_name='照片类型')),
                ('space', models.FloatField(default=0, verbose_name='附件大小（KB)')),
                ('width', models.FloatField(default=0, verbose_name='原图宽度')),
                ('height', models.FloatField(default=0, verbose_name='原图高度')),
                ('object_id', models.PositiveIntegerField()),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': '附件',
                'verbose_name_plural': '附件',
                'db_table': 'system_img_file',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='标题')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='发送内容')),
                ('source', models.CharField(blank=True, choices=[('android', '安卓客户端'), ('ios', '苹果客户端'), ('wechat_app', '微信APP'), ('qq_app', 'QQ APP'), ('alipay_app', '支付宝APP'), ('web', 'Web浏览器')], max_length=30, null=True, verbose_name='来源')),
                ('types', models.SmallIntegerField(choices=[(1, '新闻'), (2, '通知')], default=3, verbose_name='类型')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='生效时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='失效时间')),
                ('view_count', models.IntegerField(default=0, verbose_name='阅读次数')),
                ('order', models.SmallIntegerField(default=0, help_text='数字越大越靠前', verbose_name='排序')),
                ('is_top', models.BooleanField(default=False, help_text='置顶后将在首页显示', verbose_name='是否置顶')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
            ],
            options={
                'verbose_name': '新闻及通知',
                'verbose_name_plural': '新闻及通知',
                'db_table': 'system_news',
                'ordering': ['-order'],
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.SmallIntegerField(choices=[(1, '首页轮播')], default=1, verbose_name='类型')),
                ('desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='描述1')),
                ('tips', models.CharField(blank=True, max_length=255, null=True, verbose_name='描述2')),
                ('order', models.SmallIntegerField(default=0, help_text='数字越大越靠前', verbose_name='排序')),
                ('img', models.ImageField(upload_to='silder', verbose_name='图片地址')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('target_url', models.URLField(blank=True, null=True, verbose_name='点击后的跳转地址')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
            ],
            options={
                'verbose_name': '轮播图配置',
                'verbose_name_plural': '轮播图配置',
                'db_table': 'system_slider',
                'ordering': ['-order'],
            },
        ),
    ]
