# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-27 05:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mall', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='购买数量')),
                ('status', models.SmallIntegerField(choices=[(10, '购物车'), (11, '已提交'), (12, '已支付'), (13, '已发货'), (14, '已完成'), (15, '已删除')], default=10, verbose_name='状态')),
                ('name', models.CharField(max_length=128, verbose_name='商品名称')),
                ('img', models.ImageField(blank=True, max_length=256, null=True, upload_to='', verbose_name='商品主图')),
                ('price', models.IntegerField(default=5, verbose_name='销售价（积分）')),
                ('origin_price', models.FloatField(default=0, verbose_name='原价')),
                ('amount', models.FloatField(default=0, verbose_name='总和')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
            ],
            options={
                'verbose_name': '我的购物车',
                'verbose_name_plural': '我的购物车',
                'db_table': 'mine_cart',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.Product', verbose_name='产品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '我的收藏',
                'verbose_name_plural': '我的收藏',
                'db_table': 'mine_collection',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=32, verbose_name='订单号')),
                ('buy_count', models.IntegerField(default=1, verbose_name='商品总数')),
                ('buy_amount', models.FloatField(default=1, verbose_name='商品总额')),
                ('to_user', models.CharField(max_length=32, verbose_name='收货人')),
                ('to_area', models.CharField(max_length=256, verbose_name='省市区')),
                ('to_addr', models.CharField(max_length=256, verbose_name='收货地址')),
                ('to_phone', models.CharField(max_length=32, verbose_name='联系电话')),
                ('remark', models.CharField(blank=True, max_length=128, null=True, verbose_name='备注')),
                ('express_type', models.CharField(blank=True, max_length=32, null=True, verbose_name='快递')),
                ('express_no', models.CharField(blank=True, max_length=32, null=True, verbose_name='运单号')),
                ('status', models.SmallIntegerField(choices=[(10, '购物车'), (11, '已提交'), (12, '已支付'), (13, '已发货'), (14, '已完成'), (15, '已删除')], default=11, verbose_name='交易状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='购买用户')),
            ],
            options={
                'verbose_name': '订单列表',
                'verbose_name_plural': '订单列表',
                'db_table': 'mine_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='mine.Order', verbose_name='订单'),
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.Product', verbose_name='产品'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
